all:
  hosts:
    opi-red:
      ansible_host: 172.31.240.11
      ip: 172.31.240.11
      access_ip: 172.31.240.11
    opi-orange:
      ansible_host: 172.31.240.12
      ip: 172.31.240.12
      access_ip: 172.31.240.12
    opi-yellow:
      ansible_host: 172.31.240.13
      ip: 172.31.240.13
      access_ip: 172.31.240.13
    opi-green:
      ansible_host: 172.31.240.14
      ip: 172.31.240.14
      access_ip: 172.31.240.14
    opi-blue:
      ansible_host: 172.31.240.15
      ip: 172.31.240.15
      access_ip: 172.31.240.15
    opi-purple:
      ansible_host: 172.31.240.16
      ip: 172.31.240.16
      access_ip: 172.31.240.16
    opi-white:
      ansible_host: 172.31.240.17
      ip: 172.31.240.17
      access_ip: 172.31.240.17
  children:
    orangepis:
      hosts:
        opi-red:
        opi-orange:
        opi-yellow:
        opi-green:
        opi-blue:
        opi-purple:
        opi-white:
      vars:
        node_labels:
          hw: orange-pi5
    kube_control_plane:
      hosts:
        opi-red:
        opi-orange:
    kube_node:
      hosts:
        opi-yellow:
        opi-green:
        opi-blue:
        opi-purple:
        opi-white:
    etcd:
      hosts:
        opi-red:
        opi-orange:
        opi-yellow:
      vars:
        node_labels:
          etcd_node: "true"
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
