all:
  hosts:
    opi-red:
      ansible_host: 192.168.1.100
      ip: 192.168.1.100
      access_ip: 192.168.1.100
    opi-orange:
      ansible_host: 192.168.1.101
      ip: 192.168.1.101
      access_ip: 192.168.1.101
    opi-yellow:
      ansible_host: 192.168.1.102
      ip: 192.168.1.102
      access_ip: 192.168.1.102
    opi-green:
      ansible_host: 192.168.1.103
      ip: 192.168.1.103
      access_ip: 192.168.1.103
    opi-blue:
      ansible_host: 192.168.1.104
      ip: 192.168.1.104
      access_ip: 192.168.1.104
    opi-purple:
      ansible_host: 192.168.1.105
      ip: 192.168.1.105
      access_ip: 192.168.1.105
    opi-white:
      ansible_host: 192.168.1.106
      ip: 192.168.1.106
      access_ip: 192.168.1.106
  children:
    orangepis:
      hosts:
        opi-red:
        opi-orange:
        opi-yellow:
        opi-green:
        opi-blue:
        opi-purple:
        opi-white:
      vars:
        node_labels:
          hw: orangepi
    kube_control_plane:
      hosts:
        opi-red:
        opi-orange:
    kube_node:
      hosts:
        opi-yellow:
        opi-green:
        opi-blue:
        opi-purple:
        opi-white:
    etcd:
      hosts:
        opi-red:
        opi-orange:
        opi-yellow:
      vars:
        node_labels:
          etcd_node: "true"
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
